FROM robotastic/trunk-recorder:latest

##
## COMMON CONFIGURATION
##

##
## CONFIGURE 
##

##
## STARTUP CONFIGURATION
##
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["trunk-recorder", "--config=/app/config.json"]
