version: "3"
services:
##
## NGINX PROXY MANAGER CONTAINER
##
  proxy:
    container_name: proxy
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    logging:
      options:
        {"max-size":"10m", "max-file":"5"}
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - 81:81
    networks:
      - app-external
      - app-internal
    volumes:
      - ./proxy/storage:/data
      - ./storage/certificates:/etc/letsencrypt

  ##
  ## TRUNK RECORDER CONTAINER
  ##
  trunk-recorder:
    container_name: trunk-recorder
    build:
      context: ./trunk-recorder
      target: trunk-recorder
    restart: unless-stopped
    privileged: true
    logging:
      options:
        {"max-size":"10m", "max-file":"5"}
    env_file:
      - .env
    networks:
      - app-internal
    volumes:
      - ./trunk-recorder/storage:/app/storage
      - ./trunk-recorder/templates:/app/templates
      - ./storage/recordings:/app/recordings
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /dev/bus/usb:/dev/bus/usb

  ##
  ## RADIO CONTAINER
  ##
  radio:
    container_name: radio
    build:
      context: ./radio
      target: radio
    restart: unless-stopped
    privileged: true
    logging:
      options:
        {"max-size":"10m", "max-file":"5"}
    env_file:
      - .env
    networks:
      - app-internal
    volumes:
      - ./radio/storage:/app/storage
      - ./radio/templates:/app/templates
      - ./storage/recordings:/app/recordings

  ##
  ## ICECAST CONTAINER
  ##
  icecast:
    container_name: icecast
    build:
      context: ./icecast
      target: icecast
    restart: unless-stopped
    privileged: true
    logging:
      options:
        {"max-size":"10m", "max-file":"5"}
    env_file:
      - .env
    networks:
      - app-internal
    volumes:
      - ./icecast/storage:/app/storage
      - ./icecast/templates:/app/templates
      - ./storage/recordings:/app/recordings

  ##
  ## LIQUIDSOAP CONTAINER
  ##
  liquidsoap:
    container_name: liquidsoap
    build:
      context: ./liquidsoap
      target: liquidsoap
    restart: unless-stopped
    privileged: true
    logging:
      options:
        {"max-size":"10m", "max-file":"5"}
    env_file:
      - .env
    networks:
      - app-internal
    volumes:
      - ./liquidsoap/storage:/app/storage
      - ./liquidsoap/templates:/app/templates
      - ./storage/recordings:/app/recordings

##
## NETWORKS (INTERNAL & EXTERNAL)
##
networks:
  app-internal:
  app-external:
    external: true
