version: "3"
services:
##
## NGINX PROXY MANAGER CONTAINER
##
  proxy:
    container_name: proxy
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - 81:81
    networks:
      - app-external
      - app-internal
    volumes:
      - ./nginx-proxy-manager/storage:/data
      - ./storage/certificates:/etc/letsencrypt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

##
## TRUNK RECORDER CONTAINER
##
  trunk-recorder:
    container_name: trunk-recorder
    build:
      context: ./trunk-recorder
    restart: unless-stopped
    privileged: true
    logging:
      options:
        {"max-size":"10m", "max-file":"5"}
    env_file:
      - .env
    networks:
      - app-internal
    volumes:
      - ./trunk-recorder/storage:/app/storage
      - ./trunk-recorder/templates:/app/templates
      - ./storage/recordings:/app/recordings
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /dev/bus/usb:/dev/bus/usb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

##
## RADIO CONTAINER
##
  radio:
    container_name: radio
    build:
      context: ./radio
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-internal
    volumes:
      - ./radio/storage:/app/storage
      - ./storage/recordings:/app/recordings
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

##
## ICECAST CONTAINER
##
  icecast:
    container_name: icecast
    build:
      context: ./icecast
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-internal
    volumes:
      - ./icecast/templates:/app/templates
      - ./icecast/storage:/app/storage
      - ./storage/recordings:/app/recordings
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

##
## LIQUIDSOAP CONTAINER
##
  liquidsoap:
    container_name: liquidsoap
    build:
      context: ./liquidsoap
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-internal
    volumes:
      - ./liquidsoap/templates:/app/templates
      - ./liquidsoap/storage:/app/storage
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

##
## NETWORKS (INTERNAL & EXTERNAL)
##
networks:
  app-internal:
  app-external:
    external: true
