version: "3"
services:
  ##
  ## PROXY CONTAINER
  ##
  proxy:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ./data/proxy:/data
      - ./data/proxy/certificates:/etc/letsencrypt
    env_file:
      - .env
    networks:
      - app-ext
      - app-int

  ##
  ## TRUNK-RECORDER CONTAINER
  ##
  recorder:
    image: "robotastic/trunk-recorder:latest"
    container_name: recorder
    restart: unless-stopped
    privileged: true
    command: ["trunk-recorder","--config=/app/config.json"]
    logging:
      options:
        {"max-size":"10m", "max-file":"5"}
    volumes:
      - ./data/recorder:/app
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /dev/bus/usb:/dev/bus/usb
    env_file:
      - .env
    networks:
      - app-int

  ##
  ## RADIO WEB CONTAINER
  ##
  radio:
    image: docker.io/chuot/rdio-scanner:latest
    container_name: radio
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data/radio:/app/data
    env_file:
      - .env
    networks:
      - app-int

  ##
  ## ICECAST SERVER
  ##
  icecast:
    image: moul/icecast
    volumes:
      - ./data/icecast/logs:/var/log/icecast2
      - ./data/icecast/config:/etc/icecast2
      - ./data/icecast/icecast.xml:/etc/icecast2/icecast.xml
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - app-int

##
## NETWORKS (INTERNAL & EXTERNAL)
##
networks:
  app-int:
  app-ext:
    external: true
